In [3]:
#Import libraries
import numpy as np 
import pandas as pd 

#Read clean data 
sales= pd.read_csv('Clean_sales.csv')
forecast= pd.read_csv('Clean_forecast.csv')

# Data model

In [5]:
data_model=sales.merge(forecast,how= "left", on=["CountryRegion","Brand","Year"])
#check 
data_model

,ProductKey,Product_Name,Brand,Color,Subcategory,Category,CustomerKey,Customer_Code,Name,Education,...,Continent,City,State,CountryRegion,OrderDate,Quantity,Net_Price,Year,sales,Forecast
0,2492,Cigarette Lighter Adapter for Contoso Phones E...,Contoso,Cell phones Accessories,Cell phones Accessories,Cell phones,18813,CS551,Unknown,Unknown,...,North America,Spokane,Washington,United States,2008-01-01,1,23.7405,2008,23.7405,NaN
1,1763,MGS Flight Simulator 2000 M410,Tailspin Toys,Download Games,Download Games,Games and Toys,4751,15750,"Martinez, Kaitlin",Partial College,...,North America,Bellflower,California,United States,2008-01-01,1,94.7625,2008,94.7625,NaN
2,1763,MGS Flight Simulator 2000 M410,Tailspin Toys,Download Games,Download Games,Games and Toys,4760,15759,"Brooks, Erin",Bachelors,...,North America,Beaverton,Oregon,United States,2008-01-01,1,94.7625,2008,94.7625,NaN
3,1763,MGS Flight Simulator 2000 M410,Tailspin Toys,Download Games,Download Games,Games and Toys,4764,15763,"Young, Xavier",Partial College,...,North America,Walla Walla,Washington,United States,2008-01-01,1,94.7625,2008,94.7625,NaN
4,1763,MGS Flight Simulator 2000 M410,Tailspin Toys,Download Games,Download Games,Games and Toys,4773,15772,"Anderson, Christopher",Partial High School,...,North America,San Gabriel,California,United States,2008-01-01,1,94.7625,2008,94.7625,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
80233,1445,"The Phone Company Touch Screen Phones 26-1.4"" ...",The Phone Company,Touch Screen Phones,Touch Screen Phones,Cell phones,19036,CS952,Unknown,Unknown,...,North America,Worcester,Massachusetts,United States,2009-12-31,4,214.4000,2009,857.6000,1910593.0
80234,2425,Litware Tower Fan E501 Yellow,Litware,Fans,Fans,Home Appliances,19036,CS952,Unknown,Unknown,...,North America,Worcester,Massachusetts,United States,2009-12-31,4,31.9920,2009,127.9680,3380755.0
80235,1383,Contoso Dual Handset Cordless Phone System E20...,Contoso,Home & Office Phones,Home & Office Phones,Cell phones,19036,CS952,Unknown,Unknown,...,North America,Worcester,Massachusetts,United States,2009-12-31,4,10.3920,2009,41.5680,5306331.0
80236,2197,Adventure Works Desk Lamp E1200 Black,Adventure Works,Lamps,Lamps,Home Appliances,19036,CS952,Unknown,Unknown,...,North America,Worcester,Massachusetts,United States,2009-12-31,4,23.9920,2009,95.9680,4227349.0
80237,526,WWI LCD17W E200 Black,Wide World Importers,Monitors,Monitors,Computers,19036,CS952,Unknown,Unknown,...,North America,Worcester,Massachusetts,United States,2009-12-31,4,103.2000,2009,412.8000,3130149.0

In [6]:
#Validation if the releationship is correct or no 
#and i will do it by get the Groupby of data_model when year =2009 same in forecast data after that i will compere two columns data_model.Forecast with forecast.Forecast
valid_model = data_model[data_model["Year"]==2009].groupby(
                                            ["CountryRegion",
                                             "Brand",
                                             "Year"]
                                            ).agg({"Forecast":"mean"}).rename(columns={
                                                                                        "Price":"Price"
                                                                                        }).reset_index()
valid_model

    CountryRegion                 Brand  Year   Forecast
0           China              A. Datum  2009   201487.0
1           China       Adventure Works  2009   399490.0
2           China               Contoso  2009  1173308.0
3           China              Fabrikam  2009   790074.0
4           China               Litware  2009   437443.0
5           China     Northwind Traders  2009   125153.0
6           China             Proseware  2009   567070.0
7           China      Southridge Video  2009   161494.0
8           China         Tailspin Toys  2009    58013.0
9           China     The Phone Company  2009   192708.0
10          China  Wide World Importers  2009   287140.0
11        Germany              A. Datum  2009   163113.0
12        Germany       Adventure Works  2009   358333.0
13        Germany               Contoso  2009   648264.0
14        Germany              Fabrikam  2009   901946.0
15        Germany               Litware  2009   465830.0
16        Germany     Northwind Traders  2009   112925.0
17        Germany             Proseware  2009   340014.0
18        Germany      Southridge Video  2009   176339.0
19        Germany         Tailspin Toys  2009   171986.0
20        Germany     The Phone Company  2009   130420.0
21        Germany  Wide World Importers  2009   162140.0
22  United States              A. Datum  2009  1413184.0
23  United States       Adventure Works  2009  4227349.0
24  United States               Contoso  2009  5306331.0
25  United States              Fabrikam  2009  6975799.0
26  United States               Litware  2009  3380755.0
27  United States     Northwind Traders  2009   673840.0
28  United States             Proseware  2009  2285575.0
29  United States      Southridge Video  2009  1305722.0
30  United States         Tailspin Toys  2009   370525.0
31  United States     The Phone Company  2009  1910593.0
32  United States  Wide World Importers  2009  3130149.0

In [7]:
valid_model["Forecast_true"] = forecast.Forecast
valid_model

    CountryRegion                 Brand  Year   Forecast  Forecast_true
0           China              A. Datum  2009   201487.0         201487
1           China       Adventure Works  2009   399490.0         399490
2           China               Contoso  2009  1173308.0        1173308
3           China              Fabrikam  2009   790074.0         790074
4           China               Litware  2009   437443.0         437443
5           China     Northwind Traders  2009   125153.0         125153
6           China             Proseware  2009   567070.0         567070
7           China      Southridge Video  2009   161494.0         161494
8           China         Tailspin Toys  2009    58013.0          58013
9           China     The Phone Company  2009   192708.0         192708
10          China  Wide World Importers  2009   287140.0         287140
11        Germany              A. Datum  2009   163113.0         163113
12        Germany       Adventure Works  2009   358333.0         358333
13        Germany               Contoso  2009   648264.0         648264
14        Germany              Fabrikam  2009   901946.0         901946
15        Germany               Litware  2009   465830.0         465830
16        Germany     Northwind Traders  2009   112925.0         112925
17        Germany             Proseware  2009   340014.0         340014
18        Germany      Southridge Video  2009   176339.0         176339
19        Germany         Tailspin Toys  2009   171986.0         171986
20        Germany     The Phone Company  2009   130420.0         130420
21        Germany  Wide World Importers  2009   162140.0         162140
22  United States              A. Datum  2009  1413184.0        1413184
23  United States       Adventure Works  2009  4227349.0        4227349
24  United States               Contoso  2009  5306331.0        5306331
25  United States              Fabrikam  2009  6975799.0        6975799
26  United States               Litware  2009  3380755.0        3380755
27  United States     Northwind Traders  2009   673840.0         673840
28  United States             Proseware  2009  2285575.0        2285575
29  United States      Southridge Video  2009  1305722.0        1305722
30  United States         Tailspin Toys  2009   370525.0         370525
31  United States     The Phone Company  2009  1910593.0        1910593
32  United States  Wide World Importers  2009  3130149.0        3130149

In [8]:
def valiation(x,y): #This function to return if Forecast and Forecast_true same or not 
    if x == y :
        return True
    else:
        return False
valid_model["validation"] = valid_model.apply(lambda x: valiation(x["Forecast"], x["Forecast_true"]), axis=1)
#show there is Fasle meaning there is value not same or no
valid_model["validation"].unique()

array([ True])

**Note**

After this valiation we find the data_model data is correct relationship to i can use it as date model and this data connect it with both Sales and Forecast.

In [9]:
#load 
data_model.to_csv("data_model.csv",index=False)